sudo: required
before_install:
  - npm install -g node-gyp
  - npm install better-sqlite3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
language: node_js
node_js:
 - "node"